In [1]:
import pandas as pd

In [3]:
cols=['YEAR','1','2','3','4','5','6','7','8','9','10','11','12','ANUAL']
rain =pd.read_csv('./precipitaciones/precipitaciones.csv', names=cols)
rain

,YEAR,1,2,3,4,5,6,7,8,9,10,11,12,ANUAL
0,2000,4.8,10.8,12.1,10.7,18.1,23.1,23.9,24.4,21.0,14.8,8.8,7.6,15.0
1,2001,7.2,8.5,12.3,13.7,16.8,23.4,24.2,25.6,20.4,16.2,8.1,4.2,15.1
2,2002,7.2,9,11.3,13.7,15.6,23.5,24.8,23.7,19.7,14.8,9.9,8.7,15.2
3,2003,6.1,6.8,12.3,13.4,18.7,25.5,25.9,27.2,21.8,14.0,10.4,6.8,15.8
4,2004,7.6,8.1,9.4,12.4,15.1,24.5,25.6,24.1,22.3,15.6,9.2,7.4,15.1
5,2005,5.8,5.2,10.9,14.3,19.2,25.1,26.6,25.7,20.6,15.4,8.6,6.2,15.4
6,2006,5.6,6.7,11.3,14.9,19.7,23.5,27.3,24.2,22.0,16.9,11.9,6.6,15.9
7,2007,6.5,9.3,10.1,13.2,16.4,20.2,24.7,23.7,21.2,15.0,9.1,6.3,14.7
8,2008,8.0,9.3,10.9,14.0,15.5,21.2,25.0,25.7,19.8,14.6,7.9,6.3,14.9
9,2009,5.2,7.9,12.4,12.6,19.3,23.7,26.3,27.5,21.5,17.3,11.5,6.2,16.0
10,2010,5.4,6.4,9.3,14.3,16.2,21.1,27.5,26.0,21.3,14.1,8.7,6.2,14.8
11,2011,6.4,8.5,10.0,16.7,19.1,22.8,25.1,25.9,22.7,17.2,11.2,6.9,16.1
12,2012,6.7,6.2,11.9,11.6,19.2,24.5,26.2,26.9,21.2,15.0,10.1,6.8,15.6
13,2013,6.5,6.9,9.4,12.8,15.0,21.3,27.3,26.7,22.4,16.5,9.2,6.3,15.1
14,2014,8.0,7.3,11.6,16.2,18.1,22.4,24.9,25.7,21.9,18.2,11.2,7.3,16.1
15,2015,6.4,"6,8",11.7,14.7,19.9,24.5,29.6,25.4,NaN,NaN,NaN,NaN,17.3